services:
  ollama:
    image: ollama/ollama:latest
    container_name: techcorp_ollama
    volumes:
      - ./ollama_data:/root/.ollama
      - ./ollama_server:/app/ollama_server
      - ../../models:/app/models
    environment:
      - OLLAMA_ORIGINS="*"
    restart: unless-stopped

  frontend:
    image: remigeslin/socket-chat:v1
    container_name: techcorp_frontend
    ports:
      - "3000:3000"
    environment:
      - INFERENCE_TYPE=ollama
      - INFERENCE_URL=http://ollama:11434
      - MODEL_NAME=techcorp-financial-audited
    depends_on:
      - ollama
    restart: unless-stopped
